############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

# [[main]]
# name = "About"
# url = "/about"
# weight = 2

[[main]]
name = "Services"
url = "/services"
weight = 3

#[[main]]
#name = "Subscribe for weekly Growth Insights"
#url = "https://theuncomfortzone.substack.com"
#weight = 4

[[main]]
name = "Blog"
url = "/blog"
weight = 5

[[main]]
name = "Freebies"
url = "/freebies"
weight = 6
#[[main]]
#name = "Elements"
#url = "/elements"
#weight = 3

#[[main]]
#weight = 4
#name = "Pages"

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "/blog"

#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "/contact"

#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "/authors"

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"


# footer menu
[[footer]]
name = "About Me"
url = "/authors/trung-nguyen/"
weight = 1

[[footer]]
name = "Unlock your growth potential"
url = "https://theuncomfortzone.substack.com/"
weight = 2

[[footer]]
name = "Services"
url = "/services"
weight = 3

[[footer]]
name = "Freebies"
url = "/freebies"
weight = 4
